// Galaxy catalog — distances & facts from NASA/IPAC public references (static, no API key).

export const MILKY_WAY = {
  id: 'milky_way',
  name: 'Milky Way',
  type: 'Barred spiral galaxy',
  visual: 'barred',
  palette: ['#fff8e0', '#e8c86a', '#9a7ad4', '#3a2878', '#12082a'],
  discRadius: 130,
  pickRadius: 90,
  ly: 0,
  tilt: -0.65,
  spin: 0.4,
  facts: [
    'Our Sun is one of 200+ billion stars here.',
    'About 100,000 light-years across.',
    'A barred spiral with four major arms.',
  ],
  story: 'This is the Milky Way — our home galaxy! It is a vast spiral city of stars, and our entire solar system is just one tiny spark drifting inside one of its quiet arms.',
};

export const LOCAL_GROUP = [
  MILKY_WAY,
  {
    id: 'andromeda',
    name: 'Andromeda Galaxy',
    short: 'M31',
    type: 'Spiral galaxy',
    visual: 'spiral',
    palette: ['#f0f4ff', '#b8c8e8', '#6880b8', '#384878', '#182040'],
    x: 300, y: 0, z: 80,
    discRadius: 75,
    pickRadius: 55,
    ly: 2_537_000,
    tilt: -0.55,
    spin: -0.3,
    facts: [
      'The closest large galaxy to the Milky Way.',
      'About 2.5 million light-years away.',
      'On course to collide with us in ~4 billion years!',
    ],
    story: 'This is the Andromeda Galaxy — our biggest galactic neighbor! It looks like a fuzzy star to the naked eye, but it is an entire island of a trillion suns heading straight toward the Milky Way!',
  },
  {
    id: 'triangulum',
    name: 'Triangulum Galaxy',
    short: 'M33',
    type: 'Spiral galaxy',
    visual: 'spiral',
    palette: ['#e8f0ff', '#a8b8d8', '#6888b0', '#305080', '#102040'],
    x: -200, y: 10, z: -140,
    discRadius: 48,
    pickRadius: 38,
    ly: 2_730_000,
    tilt: -0.5,
    spin: 0.6,
    facts: [
      'The third-largest galaxy in our Local Group.',
      'About 3 million light-years away.',
      'Full of glowing star-birth regions.',
    ],
    story: 'Meet the Triangulum Galaxy, a gentle spiral parked near Andromeda. It is smaller than our Milky Way but packed with pink clouds where brand-new stars are being born.',
  },
  {
    id: 'lmc',
    name: 'Large Magellanic Cloud',
    short: 'LMC',
    type: 'Irregular galaxy',
    visual: 'irregular',
    palette: ['#ffe8d0', '#d8a898', '#a87888', '#684860', '#301828'],
    x: -150, y: -20, z: 220,
    discRadius: 40,
    pickRadius: 32,
    ly: 163_000,
    tilt: -0.35,
    spin: 0.2,
    facts: [
      'A satellite galaxy orbiting the Milky Way.',
      'About 163,000 light-years away.',
      'Home to the Tarantula Nebula — a star factory!',
    ],
    story: 'The Large Magellanic Cloud is a fluffy irregular galaxy dancing around our Milky Way! Southern stargazers see it like a detached piece of the Milky Way glowing in the night.',
  },
  {
    id: 'smc',
    name: 'Small Magellanic Cloud',
    short: 'SMC',
    type: 'Irregular galaxy',
    visual: 'irregular',
    palette: ['#f0e0d8', '#c8a0a0', '#987888', '#584858', '#281820'],
    x: -240, y: 30, z: 260,
    discRadius: 28,
    pickRadius: 24,
    ly: 200_000,
    tilt: -0.4,
    spin: -0.15,
    facts: [
      'Another satellite of the Milky Way.',
      'About 200,000 light-years away.',
      'Looks like a small glowing cloud in the south.',
    ],
    story: 'The Small Magellanic Cloud is a tiny galactic companion — a wispy irregular galaxy slowly being pulled apart by the Milky Way\'s gravity. Small but mighty beautiful!',
  },
];

export const DEEP_GALAXIES = [
  {
    id: 'sombrero',
    name: 'Sombrero Galaxy',
    short: 'M104',
    type: 'Lenticular galaxy',
    visual: 'lenticular',
    palette: ['#fffae8', '#d8c888', '#887858', '#403828', '#181008'],
    x: 420, y: 40, z: -380,
    discRadius: 42,
    pickRadius: 34,
    ly: 29_300_000,
    tilt: -1.15,
    spin: 0.5,
    facts: ['55 million light-years away.', 'A dark dust lane wraps its glowing rim.', 'Looks like a hat floating in space!'],
    story: 'The Sombrero Galaxy wears a brilliant white brim with a dark dust lane — like a fancy hat tilted in the cosmos! It is one of the most photogenic galaxies ever photographed.',
  },
  {
    id: 'whirlpool',
    name: 'Whirlpool Galaxy',
    short: 'M51',
    type: 'Grand-design spiral',
    visual: 'spiral',
    palette: ['#f0f8ff', '#c0d0f0', '#8098c8', '#4868a0', '#203060'],
    x: -520, y: -30, z: 280,
    discRadius: 50,
    pickRadius: 40,
    ly: 23_000_000,
    tilt: -0.6,
    spin: 0.8,
    facts: ['23 million light-years away.', 'Perfect spiral arms wrapping a companion.', 'One of the first galaxies whose spiral shape was seen.'],
    story: 'The Whirlpool Galaxy is a cosmic pinwheel! Its perfect spiral arms wrap around a smaller companion galaxy, like two dancers spinning together in the void.',
  },
  {
    id: 'pinwheel',
    name: 'Pinwheel Galaxy',
    short: 'M101',
    type: 'Spiral galaxy',
    visual: 'spiral',
    palette: ['#fff8f0', '#d0e0f8', '#90a8d0', '#5070a8', '#284878'],
    x: 680, y: 60, z: 420,
    discRadius: 55,
    pickRadius: 42,
    ly: 21_000_000,
    tilt: -0.45,
    spin: 0.3,
    facts: ['21 million light-years away.', 'About 170,000 light-years across — bigger than the Milky Way!', 'Arms are dotted with star-forming regions.'],
    story: 'The Pinwheel Galaxy is enormous — even bigger than our Milky Way! Its sprawling spiral arms are studded with pink stellar nurseries where new suns ignite.',
  },
  {
    id: 'cigar',
    name: 'Cigar Galaxy',
    short: 'M82',
    type: 'Starburst galaxy',
    visual: 'irregular',
    palette: ['#ffe0c8', '#d89078', '#a86058', '#683840', '#301820'],
    x: -380, y: 80, z: -520,
    discRadius: 38,
    pickRadius: 30,
    ly: 12_000_000,
    tilt: -1.4,
    spin: 0.1,
    facts: ['12 million light-years away.', 'Stars are being born ten times faster than in the Milky Way!', 'Red glow from countless supernova explosions.'],
    story: 'The Cigar Galaxy is a cosmic firecracker! It is exploding with new stars and supernovae, blazing red and orange like a cigar lit at both ends.',
  },
  {
    id: 'black_eye',
    name: 'Black Eye Galaxy',
    short: 'M64',
    type: 'Spiral galaxy',
    visual: 'spiral',
    palette: ['#f0f0ff', '#c0c0e0', '#8080b8', '#484880', '#202048'],
    x: 180, y: -50, z: 620,
    discRadius: 36,
    pickRadius: 28,
    ly: 17_000_000,
    tilt: -0.7,
    spin: -0.5,
    facts: ['17 million light-years away.', 'A dark dust band gives it a "black eye".', 'Inner stars orbit opposite to the outer disk!'],
    story: 'The Black Eye Galaxy looks like it got punched in the face! A thick lane of dust hides the stars behind it, making a dramatic dark bruise across its glowing face.',
  },
  {
    id: 'centaurus_a',
    name: 'Centaurus A',
    short: 'NGC 5128',
    type: 'Elliptical galaxy',
    visual: 'elliptical',
    palette: ['#fff0d8', '#d8b888', '#a08060', '#604838', '#302018'],
    x: -620, y: -60, z: -200,
    discRadius: 52,
    pickRadius: 40,
    ly: 13_000_000,
    tilt: -1.0,
    spin: 0.4,
    facts: ['13 million light-years away.', 'A giant elliptical galaxy with a dark dust band.', 'Shoots huge jets of energy from a supermassive black hole!'],
    story: 'Centaurus A is a monster elliptical galaxy with a secret — a supermassive black hole shooting jets of energy across space! A dark dust lane cuts across its glowing heart.',
  },
  {
    id: 'sunflower',
    name: 'Sunflower Galaxy',
    short: 'M63',
    type: 'Spiral galaxy',
    visual: 'spiral',
    palette: ['#fff8e8', '#e0d0a8', '#a89878', '#686050', '#302820'],
    x: 550, y: -70, z: -480,
    discRadius: 44,
    pickRadius: 34,
    ly: 29_000_000,
    tilt: -0.55,
    spin: 0.6,
    facts: ['29 million light-years away.', 'Flocculent spiral — patchy, flower-like arms.', 'Nicknamed for its petal-shaped star patterns.'],
    story: 'The Sunflower Galaxy blooms in space! Its patchy spiral arms look like golden petals swirling around a bright center — a cosmic flower in the spring sky.',
  },
];

export const OBSERVABLE_UNIVERSE = {
  id: 'observable_universe',
  name: 'Observable Universe',
  type: 'The cosmic horizon',
  visual: 'elliptical',
  palette: ['#ffffff', '#ff88cc', '#8866cc', '#332266', '#0a0418'],
  x: 0, y: 120, z: -750,
  discRadius: 100,
  pickRadius: 80,
  ly: 46_500_000_000,
  tilt: -0.3,
  spin: 0,
  facts: [
    'About 93 billion light-years across.',
    'Contains at least two trillion galaxies.',
    'Still expanding from the Big Bang.',
  ],
  story: 'This is the edge of everything humans can ever see — the observable universe! Beyond this horizon, light has not had enough time to reach us since the Big Bang. It is the ultimate frontier.',
};
